/*
 * Generated by GitHub Copilot
 * Model: MAI-Code-1.1-Flash
 * Version: 1.0
 * Date: 2026-08-18
 * Project: DS & Algo - JavaScript (my version)
 * Description: Weighted graph implemented using a linked-list style adjacency list with Dijkstra's algorithm
 */

// ============================================================
// 1) Linked list node for each edge in the graph
// ============================================================
// Each vertex will keep a linked list of its neighbors.
// Example:
// A -> B(4) -> C(2) -> null
// This means A is connected to B with weight 4 and to C with weight 2.
class EdgeNode {
    constructor(neighborVertex, edgeWeight) {
        this.neighborVertex = neighborVertex; // the connected node
        this.edgeWeight = edgeWeight; // cost to travel to that neighbor
        this.next = null; // pointer to the next edge in the linked list
    }
}

// ============================================================
// 2) Linked list node for each vertex in the graph
// ============================================================
// Every vertex stores the head of its adjacency linked list.
class VertexNode {
    constructor(vertexName) {
        this.vertexName = vertexName; // label for this node, such as 'A'
        this.head = null; // head of the linked list of edges
    }

    // Add a neighbor to this vertex.
    connectTo(neighborVertex, edgeWeight) {
        const newEdge = new EdgeNode(neighborVertex, edgeWeight);
        newEdge.next = this.head;
        this.head = newEdge;
    }
}

// ============================================================
// 3) Weighted graph using adjacency linked lists
// ============================================================
// This is very similar to the graph in example-12.js,
// but instead of a plain array of neighbors, each vertex keeps a linked list.
class WeightedGraph {
    constructor() {
        this.vertices = new Map(); // key: vertex name, value: VertexNode
    }

    addVertex(vertexName) {
        if (!this.vertices.has(vertexName)) {
            this.vertices.set(vertexName, new VertexNode(vertexName));
        }
    }

    // In this example, the graph is undirected.
    // That means if A connects to B, then B also connects back to A.
    addEdge(startVertex, endVertex, edgeWeight) {
        if (!startVertex || !endVertex) {
            throw new Error('Both vertices are required to create an edge.');
        }

        if (edgeWeight === undefined || edgeWeight === null || edgeWeight < 0) {
            throw new Error('Edge weight must be a valid number greater than or equal to 0.');
        }

        this.addVertex(startVertex);
        this.addVertex(endVertex);

        const startNode = this.vertices.get(startVertex);
        const endNode = this.vertices.get(endVertex);

        startNode.connectTo(endVertex, edgeWeight);
        endNode.connectTo(startVertex, edgeWeight);
    }

    printGraph() {
        console.log('\nGraph structure using linked-list adjacency:');

        for (const [vertexName, vertexNode] of this.vertices) {
            const connections = [];
            let currentEdge = vertexNode.head;

            while (currentEdge) {
                connections.push(`${currentEdge.neighborVertex}(${currentEdge.edgeWeight})`);
                currentEdge = currentEdge.next;
            }

            console.log(`${vertexName} -> ${connections.join(' -> ') || 'no neighbors'}`);
        }
    }

    // ------------------------------------------------------------
    // Dijkstra's algorithm
    // ------------------------------------------------------------
    // Dijkstra finds the shortest path from one starting vertex to all other vertices.
    // It works only when all edge weights are non-negative numbers.
    dijkstra(startVertex) {
        if (!this.vertices.has(startVertex)) {
            throw new Error(`Vertex "${startVertex}" does not exist in the graph.`);
        }

        // distances[vertexName] = shortest known distance from startVertex
        const distances = new Map();

        // previous[vertexName] = previous vertex used to reach this vertex
        const previous = new Map();

        const visitedVertices = new Set();
        const unvisitedVertices = new Set(this.vertices.keys());

        // Initialize all vertices with a very large distance.
        for (const vertexName of this.vertices.keys()) {
            distances.set(vertexName, Infinity);
            previous.set(vertexName, null);
        }

        distances.set(startVertex, 0);

        while (unvisitedVertices.size > 0) {
            const currentVertex = this.getClosestUnvisitedVertex(unvisitedVertices, distances);

            if (currentVertex === null) {
                break;
            }

            unvisitedVertices.delete(currentVertex);
            visitedVertices.add(currentVertex);

            let currentEdge = this.vertices.get(currentVertex).head;

            while (currentEdge) {
                const neighborVertex = currentEdge.neighborVertex;
                const newDistance = distances.get(currentVertex) + currentEdge.edgeWeight;

                // If we found a shorter path to a neighbor, update it.
                if (!visitedVertices.has(neighborVertex) && newDistance < distances.get(neighborVertex)) {
                    distances.set(neighborVertex, newDistance);
                    previous.set(neighborVertex, currentVertex);
                }

                currentEdge = currentEdge.next;
            }
        }

        return { distances, previous };
    }

    // Find the unvisited vertex with the smallest distance.
    getClosestUnvisitedVertex(unvisitedVertices, distances) {
        let closestVertex = null;
        let smallestDistance = Infinity;

        for (const vertexName of unvisitedVertices) {
            const currentDistance = distances.get(vertexName);

            if (currentDistance < smallestDistance) {
                smallestDistance = currentDistance;
                closestVertex = vertexName;
            }
        }

        return closestVertex;
    }
}

// ------------------------------------------------------------
// Helper function to reconstruct the path from start to end
// ------------------------------------------------------------
function buildShortestPath(previousMap, startVertex, endVertex) {
    const path = [];
    let currentVertex = endVertex;

    while (currentVertex) {
        path.unshift(currentVertex);
        currentVertex = previousMap.get(currentVertex);
    }

    if (path[0] !== startVertex) {
        return [];
    }

    return path;
}

// ============================================================
// 4) Example graph
// ============================================================
// This example is weighted and connected.
// Because the graph is undirected, every edge is stored twice.
const cityGraph = new WeightedGraph();

const vertices = ['A', 'B', 'C', 'D', 'E', 'F'];
for (const city of vertices) {
    cityGraph.addVertex(city);
}

cityGraph.addEdge('A', 'B', 4);
cityGraph.addEdge('A', 'C', 2);
cityGraph.addEdge('B', 'C', 1);
cityGraph.addEdge('B', 'D', 5);
cityGraph.addEdge('C', 'D', 8);
cityGraph.addEdge('C', 'E', 10);
cityGraph.addEdge('D', 'E', 2);
cityGraph.addEdge('D', 'F', 6);
cityGraph.addEdge('E', 'F', 3);

console.log('============================================================');
console.log('Dijkstra shortest path example with weighted linked-list graph');
console.log('============================================================');
cityGraph.printGraph();

const startVertex = 'A';
const endVertex = 'F';
const result = cityGraph.dijkstra(startVertex);
const shortestDistance = result.distances.get(endVertex);
const path = buildShortestPath(result.previous, startVertex, endVertex);

console.log('\nShortest distances from ' + startVertex + ':');
for (const vertexName of vertices) {
    console.log(`${vertexName}: ${result.distances.get(vertexName)}`);
}

console.log(`\nShortest path from ${startVertex} to ${endVertex}: ${path.join(' -> ')}`);
console.log(`Total cost: ${shortestDistance}`);

// ============================================================
// What is happening here?
// ============================================================
// 1. Each vertex stores a linked list of neighboring vertices.
// 2. Every neighbor has a weight, meaning the cost to travel there.
// 3. Dijkstra checks the lowest-cost path first.
// 4. It keeps updating distances until the shortest route to all vertices is known.
// 5. The result gives the shortest route and total weight.

// Example output idea:
// A -> B(4) -> C(2)
// B -> A(4) -> C(1) -> D(5)
// ...
// Shortest path from A to F: A -> C -> B -> D -> F
// Total cost: 11
